#!/bin/bash
_swift() 
{
    declare -a cur prev shared_options
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    COMPREPLY=()
    # completions for tools, and compiler flags (non-tool)
    if [[ $COMP_CWORD == 1 ]]; then
        COMPREPLY=( $(compgen -W "build package test" -- $cur) )
        _swift_compiler
        return
    fi
    # shared options are available in all tools
    shared_options="-C --chdir --color -v --verbose -Xcc -Xlinker -Xswiftc"
    # specify for each tool
    case ${COMP_WORDS[1]} in
        (build)
            _swift_build
            ;;
        (package)
            _swift_package
            ;;
        (test)
            _swift_test
            ;;
        (*)
            _swift_compiler
            ;;
    esac
}
_swift_build()
{
    case $prev in
        (-c|--configuration)
            COMPREPLY=( $(compgen -W "debug release" -- $cur) )
            return
            ;;
        (--clean)
            COMPREPLY=( $(compgen -W "build dist" -- $cur) )
            ;;
        (--build-path)
            _filedir
            return
            ;;
    esac
    COMPREPLY+=( $(compgen -W "-c --configuration --clean --build-path $shared_options" -- $cur) )
}
_swift_package()
{
    if [[ $COMP_CWORD == 2 ]]; then
        COMPREPLY=( $(compgen -W "init fetch update generate-xcodeproj show-dependencies dump-package -h --help --version" -- $cur) )
        return
    fi

    case $prev in
        (-h|--help)
        ;;
        (--version)
        ;;
    esac

    case ${COMP_WORDS[2]} in
        (init)
            _swift_package_init
            return
        ;;
        (fetch)
            _swift_package_fetch
            return
        ;;
        (update)
            _swift_package_update
            return
        ;;
        (generate-xcodeproj)
            _swift_package_generate-xcodeproj
            return
        ;;
        (show-dependencies)
            _swift_package_show-dependencies
            return
        ;;
        (dump-package)
            _swift_package_dump-package
            return
        ;;
    esac

    COMPREPLY=( $(compgen -W "init fetch update generate-xcodeproj show-dependencies dump-package -h --help --version" -- $cur) )
}

_swift_package_init()
{
    if [[ $COMP_CWORD == 3 ]]; then
        COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc --type" -- $cur) )
        return
    fi

    case $prev in
        (-C|--chdir)
            _filedir
            return
        ;;
        (--build-path)
            _filedir
            return
        ;;
        (--color)
            COMPREPLY=( $(compgen -W "auto always never" -- $cur) )
            return
        ;;
        (--enable-code-coverage)
        ;;
        (-v|--verbose)
        ;;
        (--Xcc)
            return
        ;;
        (--Xlinker)
            return
        ;;
        (--Xswiftc)
            return
        ;;
        (--type)
            COMPREPLY=( $(compgen -W "empty library executable system-module" -- $cur) )
            return
        ;;
    esac

    case ${COMP_WORDS[3]} in
    esac

    COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc --type" -- $cur) )
}

_swift_package_fetch()
{
    if [[ $COMP_CWORD == 3 ]]; then
        COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc" -- $cur) )
        return
    fi

    case $prev in
        (-C|--chdir)
            _filedir
            return
        ;;
        (--build-path)
            _filedir
            return
        ;;
        (--color)
            COMPREPLY=( $(compgen -W "auto always never" -- $cur) )
            return
        ;;
        (--enable-code-coverage)
        ;;
        (-v|--verbose)
        ;;
        (--Xcc)
            return
        ;;
        (--Xlinker)
            return
        ;;
        (--Xswiftc)
            return
        ;;
    esac

    case ${COMP_WORDS[3]} in
    esac

    COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc" -- $cur) )
}

_swift_package_update()
{
    if [[ $COMP_CWORD == 3 ]]; then
        COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc" -- $cur) )
        return
    fi

    case $prev in
        (-C|--chdir)
            _filedir
            return
        ;;
        (--build-path)
            _filedir
            return
        ;;
        (--color)
            COMPREPLY=( $(compgen -W "auto always never" -- $cur) )
            return
        ;;
        (--enable-code-coverage)
        ;;
        (-v|--verbose)
        ;;
        (--Xcc)
            return
        ;;
        (--Xlinker)
            return
        ;;
        (--Xswiftc)
            return
        ;;
    esac

    case ${COMP_WORDS[3]} in
    esac

    COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc" -- $cur) )
}

_swift_package_generate-xcodeproj()
{
    if [[ $COMP_CWORD == 3 ]]; then
        COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc --output" -- $cur) )
        return
    fi

    case $prev in
        (-C|--chdir)
            _filedir
            return
        ;;
        (--build-path)
            _filedir
            return
        ;;
        (--color)
            COMPREPLY=( $(compgen -W "auto always never" -- $cur) )
            return
        ;;
        (--enable-code-coverage)
        ;;
        (-v|--verbose)
        ;;
        (--Xcc)
            return
        ;;
        (--Xlinker)
            return
        ;;
        (--Xswiftc)
            return
        ;;
        (--output)
            _filedir
            return
        ;;
    esac

    case ${COMP_WORDS[3]} in
    esac

    COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc --output" -- $cur) )
}

_swift_package_show-dependencies()
{
    if [[ $COMP_CWORD == 3 ]]; then
        COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc --format" -- $cur) )
        return
    fi

    case $prev in
        (-C|--chdir)
            _filedir
            return
        ;;
        (--build-path)
            _filedir
            return
        ;;
        (--color)
            COMPREPLY=( $(compgen -W "auto always never" -- $cur) )
            return
        ;;
        (--enable-code-coverage)
        ;;
        (-v|--verbose)
        ;;
        (--Xcc)
            return
        ;;
        (--Xlinker)
            return
        ;;
        (--Xswiftc)
            return
        ;;
        (--format)
            COMPREPLY=( $(compgen -W "text dot json" -- $cur) )
            return
        ;;
    esac

    case ${COMP_WORDS[3]} in
    esac

    COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc --format" -- $cur) )
}

_swift_package_dump-package()
{
    if [[ $COMP_CWORD == 3 ]]; then
        COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc --input" -- $cur) )
        return
    fi

    case $prev in
        (-C|--chdir)
            _filedir
            return
        ;;
        (--build-path)
            _filedir
            return
        ;;
        (--color)
            COMPREPLY=( $(compgen -W "auto always never" -- $cur) )
            return
        ;;
        (--enable-code-coverage)
        ;;
        (-v|--verbose)
        ;;
        (--Xcc)
            return
        ;;
        (--Xlinker)
            return
        ;;
        (--Xswiftc)
            return
        ;;
        (--input)
            _filedir
            return
        ;;
    esac

    case ${COMP_WORDS[3]} in
    esac

    COMPREPLY=( $(compgen -W "-C --chdir --build-path --color --enable-code-coverage -v --verbose --Xcc --Xlinker --Xswiftc --input" -- $cur) )
}

_swift_test()
{
    case $prev in
        (-s|--specifier)
            return
            ;;
    esac
    COMPREPLY=( $(compgen -W "-s --specifier -l --list-tests --skip-build --version $shared_options" -- $cur) )
}
_swift_compiler()
{
    case $prev in
        (-assert-config)
            COMPREPLY=( $(compgen -W "Debug Release Unchecked DisableReplacement" -- $cur) )
            return
            ;;
        (-D|-framework|-j|-l|-module-link-name|-module-name|-num-threads|-sdk|-target-cpu|-target|-use-ld)
            return
            ;;
        (-F|-index-store-path|-I|-L|-module-cache-path)
            _filedir
            ;;
    esac
    local args
    args="-assert-config -D -framework -F -gdwarf-types -gline-tables-only \
         -gnone -g -help -index-store-path -I -j -L -l -module-cache-path \
         -module-link-name -module-name -nostdimport -num-threads -Onone \
         -Ounchecked -O -sdk -static-stdlib -suppress-warnings -target-cpu \
         -target -use-ld -version -v -warnings-as-errors -Xcc -Xlinker"
    COMPREPLY+=( $(compgen -W "$args" -- $cur))
    _filedir
}
complete -F _swift swift
